worker:
  build: .
  dockerfile: Dockerfile.worker
  #hostname: worker
  environment:
    MAX_CPU_CORES: 1
  links:
   - server

server:
  build: .
  dockerfile: Dockerfile.server
  hostname: server
  ports:
   - "5672:5672" # RabbitMQ
   - "6379:6379" # Redis
  environment:
    THETA_RESOLUTION: 30
    TIME_MAX: 10
    DTIME: 0.1
    MAX_CPU_CORES: 1
  volumes:
   - /tmp/results:/results